# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela-main-frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 577)
        MainWindow.setMinimumSize(QtCore.QSize(635, 0))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(254, 10, 181, 31))
        self.label_2.setStyleSheet("\n"
"color: rgb(0, 0, 0);\n"
"font: 15pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(254, 50, 441, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(260, 100, 441, 341))
        self.tableWidget.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 467, 320, 29))
        self.layoutWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 221, 331))
        self.label_3.setStyleSheet("image: url(:/img/icons/carrinho-de-compras.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 816, 21))
        self.menubar.setObjectName("menubar")
        self.menuClientes = QtWidgets.QMenu(self.menubar)
        self.menuClientes.setObjectName("menuClientes")
        self.menuEncerrar = QtWidgets.QMenu(self.menubar)
        self.menuEncerrar.setObjectName("menuEncerrar")
        MainWindow.setMenuBar(self.menubar)
        self.actionVenda = QtWidgets.QAction(MainWindow)
        self.actionVenda.setObjectName("actionVenda")
        self.actionVendas_do_dia = QtWidgets.QAction(MainWindow)
        self.actionVendas_do_dia.setObjectName("actionVendas_do_dia")
        self.actionVendas_Geral = QtWidgets.QAction(MainWindow)
        self.actionVendas_Geral.setObjectName("actionVendas_Geral")
        self.actionFechamento_de_caixa = QtWidgets.QAction(MainWindow)
        self.actionFechamento_de_caixa.setObjectName("actionFechamento_de_caixa")
        self.actionFechamento_de_caixa_2 = QtWidgets.QAction(MainWindow)
        self.actionFechamento_de_caixa_2.setObjectName("actionFechamento_de_caixa_2")
        self.actionAbrir_Caixa = QtWidgets.QAction(MainWindow)
        self.actionAbrir_Caixa.setObjectName("actionAbrir_Caixa")
        self.menuClientes.addAction(self.actionAbrir_Caixa)
        self.menuClientes.addAction(self.actionFechamento_de_caixa_2)
        self.menubar.addAction(self.menuClientes.menuAction())
        self.menubar.addAction(self.menuEncerrar.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Código do Produto:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Produtos"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quant"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Preço"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Total"))
        self.pushButton_4.setText(_translate("MainWindow", "Buscar"))
        self.pushButton_3.setText(_translate("MainWindow", "Finalizar"))
        self.pushButton_2.setText(_translate("MainWindow", "Troco"))
        self.pushButton.setText(_translate("MainWindow", "Remover"))
        self.menuClientes.setTitle(_translate("MainWindow", "Administar"))
        self.menuEncerrar.setTitle(_translate("MainWindow", "Encerrar"))
        self.actionVenda.setText(_translate("MainWindow", "Venda"))
        self.actionVendas_do_dia.setText(_translate("MainWindow", "Vendas do dia"))
        self.actionVendas_Geral.setText(_translate("MainWindow", "Vendas Geral"))
        self.actionFechamento_de_caixa.setText(_translate("MainWindow", "Fechamento de caixa"))
        self.actionFechamento_de_caixa_2.setText(_translate("MainWindow", "Fechamento de caixa"))
        self.actionAbrir_Caixa.setText(_translate("MainWindow", "Abrir Caixa"))
import imgimport as imgimport


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
